### PR TITLE
Add support for multiple themes

### LINKED ISSUE #46: Alternative variables dict in BULMA_SETTINGS
In some cases, a website will want to have two themes, e.g. a dark theme and a light theme. To do this while using this plugin is tricky because all the scss variables are compiled at startup. But here's what we can do:

- If an `alt_variables` dict is present in `BULMA_SETTINGS`, we compile two css files, `bulma.css` and `bulma_alt.css`
- We create a template tag for adding this other css file as well, something like `{% bulma_alt %}`

Now the client can simply add this second dict of variables and define the dark theme that way, and then add some client logic to allow switching between them by switching which template tag is called in the templates.

### PR DESCRIPTION
**Pull request by JonasUJ**
This closes #46 

It basically generates a unique bulma.css stylesheet for each theme. I also decided that we should log a warning if someone tries to use a theme they haven't defined.

### CODE REVIEW

**Comment by JonasUJ** [comment]
The checks are failing on code I didn't introduce

**Comment by lemonsaurus** [comment]
> The checks are failing on code I didn't introduce

Looks like it's just the trailing whitespace checker. Why don't you set up the `pre-commit` and just run it? It'll fix it right up.

**Comment by lemonsaurus** [comment]
To be perfectly clear, even though this PR didn't introduce this code, it's fine if you make a kaizen commit that fixes some trailing whitespace.

**Review by lemonsaurus — APPROVED** [review]
Seems to work. I'll merge and release it.

**Pull request merged**
